version: '2'

services:
  jenkins_mittax:
    build: 
       context: .
       dockerfile: jenkins.dockerfile
    ports: 
      - "8080:8080"    
    networks:
       - jenkins_mittax
  
networks:
  jenkins_mittax:
    driver: bridge
